apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template: 
    metadata:
      annotations:
        timestamp: "1"
        branch: develop
        repository: harbor.wlhiot.com:8080
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9113"
      labels:
        app: test
        app.kubernetes.io/name: test
        app.kubernetes.io/instance: test-abcxzy
        app.kubernetes.io/version: "1.6.1.6"
        app.kubernetes.io/component: project
        app.kubernetes.io/part-of: ebox
        app.kubernetes.io/managed-by: kubernetes
        app.kubernetes.io/created-by: controller-manager
    spec: 
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test
              topologyKey: kubernetes.io/hostname
      containers:
      - name: eboxtest-svr
        image: 192.168.254.29:8080/test/ebox_svr
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8221
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - mountPath: /mount
          name: eboxtest-pv
      - name: eboxtest-vue
        image: 192.168.254.29:8080/test/ebox_vue
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /vehiclemap
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
      - name: nginx-exporter
        image: fish/nginx-exporter
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9113
      initContainers:
      - name: init-sleep
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 5']
      volumes: 
      - name: eboxtest-pv
        persistentVolumeClaim:
          claimName: eboxtest-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - name: eboxtest-svr
      port: 8080
      targetPort: 8080
      nodePort: 31112
    - name: eboxtest-vue
      port: 80
      targetPort: 80
      nodePort: 31111
